### PR TITLE
Patient Onboarding Excel Implementation

### PR DESCRIPTION
**Pull request by SushantQA**

### CODE REVIEW

**Review by avinashSam — COMMENTED** [review]
Use relative xpath and clear the comments

**Comment by SushantQA** [comment]
@avinashSam Removed all the conflicts and comments please review again. Some commented code are there for further work which I will uncomment later.

**Comment by SushantQA** [comment]
> why did you change in properties file?

Variables we are passing there so, it's a change.

**Review by avinashSam — APPROVED** [review]
merge it

**Comment by SushantQA** [comment]
> merge it

Ok. Thanks!

**Pull request merged**
